name: Dragons

networks:
  dragons-network:
    driver: bridge

volumes:
  backend-build:

services:
  redis:
    image: redis:8.2
    container_name: dragons-redis
    command: [
      "redis-server",
      "--save", "60", "1",
      "--loglevel", "notice",
      "--port", "16379"
    ]
    ports:
      - "16379:16379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "16379", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    restart: unless-stopped
    networks:
      - dragons-network

  backend:
    container_name: dragons-backend
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ../backend/src:/app/src
      - backend-build:/app/build
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 40022
      REDIS_HOST: 'redis'
      REDIS_PORT: 16379
    env_file:
      - ../.env
    ports:
      - "40022:40022"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:40022/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    restart: unless-stopped
    networks:
      - dragons-network

  frontend:
    container_name: dragons-frontend
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ../frontend:/app
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 30011
    ports:
      - "30011:30011"
    restart: unless-stopped
    networks:
      - dragons-network
