name: Dragons

networks:
  dragons-network:
    driver: bridge

services:
  backend:
    container_name: dragons-backend
    build:
      context: ..
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ../backend/src:/app/src
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 40022
    ports:
      - "40022:40022"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:40022/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    restart: unless-stopped
    networks:
      - dragons-network

  frontend:
    container_name: dragons-frontend
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ../frontend:/app
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 30011
    ports:
      - "30011:30011"
    restart: unless-stopped
    networks:
      - dragons-network
